services:
  redis:
    image: redis:7-alpine
    command: ['redis-server', '--appendonly', 'yes', '--appendfsync', 'everysec']
    ports: ['6379:6379']
    volumes: ['redis-data:/data']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10
  # api:
  #   build: .
  #   command: ['node', 'dist/apps/demo/apps/demo/src/main.js']
  #   env_file: .env.example
  #   environment: { REDIS_HOST: redis }
  #   ports: ['3000:3000']
  #   depends_on:
  #     redis: { condition: service_healthy }
  # worker:
  #   build: .
  #   command: ['node', 'dist/apps/demo/apps/demo/src/worker.main.js']
  #   env_file: .env.example
  #   environment: { REDIS_HOST: redis }
  #   depends_on:
  #     redis: { condition: service_healthy }
volumes:
  redis-data:
