import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the notification persistence schema.
 *
 * Kept in exact parity with the TypeORM entities in
 * `libs/notification/src/infrastructure/persistence/typeorm/entities`:
 * - PostgreSQL BIGINT identity primary keys (strings in TypeScript).
 * - `timestamptz` timestamps with `now()` defaults.
 * - Enum-backed columns stored as varchar (no native PG enum types).
 * - JSONB notification context.
 * - Unique keys: notification identity tuple, one delivery per channel,
 *   one outbox row per delivery.
 * - Foreign keys cascade deletes from notifications down to outbox rows.
 *
 * Constraint/index names are quoted so PostgreSQL preserves their exact
 * mixed-case spelling, matching the names declared on the entities.
 */
export class CreateNotificationTables20260823000001 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Parent tables first: notification_deliveries holds a foreign key to
    // notifications, and notification_outbox holds a foreign key to
    // notification_deliveries, so each table must exist before the next
    // one can reference it.
    await this.createNotificationsTable(queryRunner);
    await this.createNotificationDeliveriesTable(queryRunner);
    await this.createNotificationOutboxTable(queryRunner);

    // Indexes come last because they only require their own table to exist.
    await this.createIndexes(queryRunner);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Exact reverse of up(): children before parents (outbox ->
    // notification_deliveries -> notifications), each dropping its indexes
    // first, so foreign keys never block a drop. IF EXISTS keeps the revert
    // safe when the objects were never created.
    await this.dropNotificationOutbox(queryRunner);
    await this.dropNotificationDeliveries(queryRunner);
    await this.dropNotifications(queryRunner);
  }

  private async createNotificationsTable(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE notifications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_event_id VARCHAR(255) NOT NULL,
        recipient_type VARCHAR(50) NOT NULL,
        recipient_id BIGINT NOT NULL,
        type VARCHAR(50) NOT NULL,
        reference_type VARCHAR(50) NOT NULL,
        reference_id VARCHAR(255) NOT NULL,
        context JSONB NOT NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_notifications_source_recipient_type"
          UNIQUE (source_event_id, recipient_type, recipient_id, type)
      )
    `);
  }

  private async createNotificationDeliveriesTable(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE notification_deliveries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        notification_id BIGINT NOT NULL,
        channel VARCHAR(50) NOT NULL,
        recipient_address VARCHAR(255) NOT NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
        attempt_count INTEGER NOT NULL DEFAULT 0,
        provider_message_id VARCHAR(255) NULL,
        last_error TEXT NULL,
        sent_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "FK_notification_deliveries_notification"
          FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE,
        CONSTRAINT "UQ_notification_deliveries_notification_channel"
          UNIQUE (notification_id, channel)
      )
    `);
  }

  private async createNotificationOutboxTable(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE notification_outbox (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        delivery_id BIGINT NOT NULL,
        published_at TIMESTAMPTZ NULL,
        publish_attempts INTEGER NOT NULL DEFAULT 0,
        last_publish_error TEXT NULL,
        next_publish_at TIMESTAMPTZ NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "FK_notification_outbox_delivery"
          FOREIGN KEY (delivery_id) REFERENCES notification_deliveries (id) ON DELETE CASCADE,
        CONSTRAINT "UQ_notification_outbox_delivery" UNIQUE (delivery_id)
      )
    `);
  }

  private async createIndexes(queryRunner: QueryRunner): Promise<void> {
    // Quoted names preserve the exact mixed-case spelling declared on the
    // entities (see class doc); unquoted names would be folded to lowercase.
    await queryRunner.query(
      `CREATE INDEX "IDX_notifications_source_event_id" ON notifications (source_event_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_notification_deliveries_notification_id" ON notification_deliveries (notification_id)`,
    );
    // Partial composite index matching the entity metadata: only unpublished
    // rows participate, keeping the publish-polling hot set small.
    await queryRunner.query(
      `CREATE INDEX "IDX_notification_outbox_publishable"
         ON notification_outbox ("created_at" ASC, "next_publish_at" ASC)
         WHERE "published_at" IS NULL`,
    );
  }

  /** Drops the outbox index and table; must run before its parent table. */
  private async dropNotificationOutbox(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_notification_outbox_publishable"`);
    await queryRunner.query(`DROP TABLE IF EXISTS notification_outbox`);
  }

  /** Drops the deliveries index and table; must run before notifications. */
  private async dropNotificationDeliveries(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_notification_deliveries_notification_id"`);
    await queryRunner.query(`DROP TABLE IF EXISTS notification_deliveries`);
  }

  /** Drops the root notifications index and table. */
  private async dropNotifications(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_notifications_source_event_id"`);
    await queryRunner.query(`DROP TABLE IF EXISTS notifications`);
  }
}
