export const BULLMQ_OPTIONS = Symbol('BULLMQ_OPTIONS');
export const BULLMQ_QUEUE_DEFINITIONS = Symbol('BULLMQ_QUEUE_DEFINITIONS');
export const BULLMQ_WORKER_DEFINITIONS = Symbol('BULLMQ_WORKER_DEFINITIONS');
